### ISSUE TITLE
SDDCX-0001 Mongo DB

### ISSUE THREAD

**Issue by Gani-23** [Gani-23/DevOPS-CA#1]
# Summary 

- Create a mongodb depl, service host it on EKS
- Test it, add data and do crud of you are okay with it via/ Travel memory application

**Comment by Gani-23** [comment]
Direct Docker compose file 
```
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  # Expose MongoDB port if needed for external access
    volumes:
      - mongo_data:/data/db  # Persist data across container restarts

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

volumes:
  mongo_data:

```
